services:
  cross-references-predictor:
    container_name: cross-references-predictor
    entrypoint: [ "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--chdir", "./src", "cross_references_predictor.drivers.rest.app:app", "--bind", "0.0.0.0:5070", "--timeout", "10000"]
    init: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=references_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OLLAMA_HOST=http://localhost:11434
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
      - PDF_ANALYSIS_SERVICE_URL=http://localhost:5060
    network_mode: host
    depends_on:
      - postgres

  pdf-layout-analysis:
    container_name: "pdf-layout-analysis"
    entrypoint: [ "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--chdir", "./src", "app:app", "--bind", "0.0.0.0:5060", "--timeout", "10000"]
    image: ghcr.io/huridocs/pdf-document-layout-analysis:0.0.32
    init: true
    restart: unless-stopped
    network_mode: host

  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: references_db
      PGPORT: ${POSTGRES_PORT:-5432}
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:4
    restart: unless-stopped
    network_mode: host
    environment:
      ADMINER_PORT: ${ADMINER_PORT:-8080}
    entrypoint: php -S 0.0.0.0:${ADMINER_PORT:-8080} -t /var/www/html

volumes:
  postgres_data:
